name: medical
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev
publish_to: 'none' 

# Application version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Asset files
  assets:
    - assets/background.png
    - assets/logo.png
